# Dockerfile for development environment
FROM ruby:2.7.4-slim
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev npm nodejs
RUN mkdir /rails_oauth_practice
WORKDIR /rails_oauth_practice
ADD Gemfile /rails_oauth_practice/Gemfile
ADD Gemfile.lock /rails_oauth_practice/Gemfile.lock
RUN gem install bundler:2.2.32
RUN bundle config set --local path './vendor/bundle'
RUN npm install --global yarn webpack webpack-cli
ADD . /rails_oauth_practice
