version: '3'

volumes:
  db_data_dev:

networks:
  example-network_dev:
    driver: bridge

services:
  db_dev:
    image: postgres:14
    container_name: db_dev
    volumes:
      - db_data_dev:/var/lib/postgresql/data/
    networks:
      - example-network_dev
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    restart: unless-stopped

  webpacker:
    image: rails-oauth-example_web_dev:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn && rm -rf /rails_oauth_practice/public/packs webpack serve --host 0.0.0.0 --mode development
    networks:
      - example-network_dev
    volumes:
      - .:/rails_oauth_practice
    ports:
      - 3035:3035

  web_dev:
    image: rails-oauth-example_web_dev:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "/rails_oauth_practice/init_dev.sh && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes: 
      - .:/rails_oauth_practice
    networks:
      - example-network_dev
    ports: 
      - "3000:3000"
    depends_on:
      - db_dev
      - webpacker
    links:
      - db_dev
      - webpacker
    restart: unless-stopped
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db_dev
      DB_NAME: rails_oauth_example_development
      DB_TEST_NAME: rails_oauth_example_test
