version: '3'

volumes:
  mysql_data:

networks:
  example-network:
    driver: bridge

services:
  db: 
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - example-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rails_oauth_practice_development
    ports:
      - "3307:3306"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]


  webpack:
    build: .
    command: ./bin/webpack-dev-server --inline true
    volumes:
      - '.:/rails_oauth_practice'
    ports:
      - '3035:3035'

  app: 
    build: .
    command: bash -c "/rails_oauth_practice/init.sh && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes: 
      - ".:/rails_oauth_practice"
    networks:
      - example-network
    ports: 
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    restart: unless-stopped
    environment:
      DB_USER: root
      DB_NAME: rails_oauth_practice_development
      DB_PASSWORD: root
      DB_HOST: db
