# Dockerfile for development environment
FROM ruby:2.7.4-slim
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev npm nodejs wget xvfb unzip

# Set up the Chrome PPA
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list

# Update the package list and install chrome
RUN apt-get update && \
        apt-get install -y gnupg wget curl unzip --no-install-recommends && \
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
        echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list && \
        apt-get update -y && \
        apt-get install -y google-chrome-stable && \
        CHROMEVER=$(google-chrome --product-version | grep -o "[^\.]*\.[^\.]*\.[^\.]*") && \
        DRIVERVER=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROMEVER") && \
        wget -q --continue -P /chromedriver "https://chromedriver.storage.googleapis.com/$DRIVERVER/chromedriver_linux64.zip" && \
        unzip /chromedriver/chromedriver* -d /chromedriver

 # Put Chromedriver into the PATH
 ENV PATH /chromedriver:$PATH


RUN mkdir /rails_oauth_practice
WORKDIR /rails_oauth_practice
ADD Gemfile /rails_oauth_practice/Gemfile
ADD Gemfile.lock /rails_oauth_practice/Gemfile.lock
RUN gem install bundler:2.2.32
RUN bundle install
RUN npm install --global yarn webpack webpack-cli
ADD . /rails_oauth_practice
