# docker-compose file to run production environment locally
version: '3'

volumes:
  db_data_prod:

networks:
  example-network_prod:
    driver: bridge

services:
  db_prod:
    image: postgres:14
    container_name: db_prod
    volumes:
      - db_data_prod:/var/lib/postgresql/data/
    networks:
      - example-network_prod
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    restart: unless-stopped

  web_prod:
    image: rails-oauth-example_web_prod:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    networks:
      - example-network_prod
    ports:
      - "3000:3000"
    depends_on:
      - db_prod
    links:
      - db_prod
    restart: unless-stopped
    environment:
      PRODUCTION_DB_USER: root
      PRODUCTION_DB_PASSWORD: root
      DB_HOST: db_prod
