version: '3'
services:
  db: 
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rails_oauth_practice_development
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
  app: 
    build: .
    command: sh -c "/rails_oauth_practice/init.sh && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes: 
      - ".:/rails_oauth_practice"
    ports: 
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: rails_oauth_practice_development
      DB_PASSWORD: root
      DB_HOST: db
      REDIS_URL: redis://redis_db:6379
